baseURL = "http://localhost:8080" # Replace with the URL where your Dev Portal will be deployed
languageCode = "en-us"

# Theme
theme = ["kamrad-shortcodes", "smol"]

# Taxonomies
[taxonomies]
spec_ref = "specs_refs"

# Permalinks
[permalinks]
specs_refs = "/spec/:title"

## Parameters
[params]
subtitle = "Kamrad, the Kuadrant's developer portal"
dateFmt = "11.05.2021 15:51"
kamwielURL = "https://kamwiel.eu.ngrok.io" # Replace with the URL of your Kuadrant cluster

[outputs]
home = [ "HTML", "RSS", "JSON"]


## Header
[menu]
[[menu.main]]
identifier = "about"
name = "About"
url = "/about"
weight = 1

[[menu.main]]
identifier = "docs"
name = "Docs"
url = "/docs/"
weight = 2

[[menu.main]]
identifier = "specs"
name = "Specs"
url = "/specs"
weight = 3

## Footer
[[menu.footer]]
name = "Github"
url = "https://github.com/3scale-labs/kamrad"
weight = 1


# I18N
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[languages]
[languages.en]
title = "Kamrad"
languageName = "English"
weight = 1

# Build
[build]
noJSConfigInAssets = true

# Security
[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^babel$', '^go$', '^npx$', '^postcss$']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']
  [security.funcs]
    getenv = ['^HUGO_']
  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']
