baseURL = "https://3scale-labs.github.io/kamrad" # Replace with the URL where your Dev Portal will be deployed
languageCode = "en-us"

# Theme
theme = "smol"

## Parameters
[params]
subtitle = "Kamrad, the Kuadrant's developer portal"
dateFmt = "11.05.2021 15:51"
kamwielURL = "https://kamwiel.eu.ngrok.io" # Replace with the URL of your Kuadrant cluster

## Header
[menu]
[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 1

[[menu.main]]
identifier = "docs"
name = "Docs"
url = "/docs/"
weight = 2

[[menu.main]]
identifier = "about"
name = "About"
url = "/about"
weight = 3

[[menu.main]]
identifier = "pong"
name = "Pong!"
url = "/pong"
weight = 4


## Footer
[[menu.footer]]
name = "Github"
url = "https://github.com/3scale-labs/kamrad"
weight = 1


# I18N
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[languages]
[languages.en]
title = "Kamrad"
languageName = "English"
weight = 1

# Build
[build]
  noJSConfigInAssets = true
