name: Generate API pages

on:
  repository_dispatch:
    types: [ api-list ]
    branches:
      - main

jobs:
  check-api-hash:
    runs-on: ubuntu-20.04
    outputs:
      needs-build: ${{ steps.check.outputs.flag }}
    steps:
      - name: Checking Kamwiel hash
        id: check
        shell: bash
        env:
          STORED_HASH: ${{ secrets.KAMWIEL_API_HASH }}
          WEBHOOK_HASH: ${{ github.event.client_payload.hash }}
        run: if [ $STORED_HASH != $WEBHOOK_HASH ]; then echo "::set-output name=flag::true"; fi

  deploy_new_apis:
    needs: check-api-hash
    if: needs.check-api-hash.outputs.needs-build == 'true'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true
          fetch-depth: 0
          ref: ${{ github.event.client_payload.ref }}

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install JS dependencies
        run: npm ci

      - name: Fetch API List
        id: fetchAPIList
        uses: fjogeleit/http-request-action@master
        with:
          method: 'GET'
          url: ${{ secrets.KAMWIEL_URL }}/apis
          customHeaders: '{"X-API-KEY": "${{ secrets.KAMWIEL_API_KEY }}"}'

      - name: Generate API pages
        run: make generate_api_pages API_LIST='${{ steps.fetchAPIList.outputs.response }}'

      - name: Build static site
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - name: Mark deploy with new hash
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'KAMWIEL_API_HASH'
          value: ${{ github.event.client_payload.hash }}
          repository: '3scale-labs/kamrad'
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          org: true
          visibility: 'all'
